Users/feature/payment gateway
eyeamkd/aagman pull request #41
Opened 2021-10-06 15:10 UTC by KunalSharma1999

2021-10-06 15:20 UTC, KunalSharma1999 commented
For now I have integrated the razorpay payment gateway. On clicking on the checkout button in the verify order pop up it opens up the razorpay payment form. I tested that out with the sample testing credit card data. There is one more issue in that while entering the form fields in that pop up there is some glitch that does not let to type. After the payment is done it redirects to the order status page. 

Though I m getting the payment in the payment gateway will have to look for the way how that received payment can be sent to the seller or the merchant.

2021-10-12 04:14 UTC, eyeamkd requested changes
Hey @KunalSharma1999 , please check the comments and resolve them

2021-10-12 04:14 UTC, eyeamkd commented on client/__mocks__/styleMock.js
> +module.exports = {};
Is this required?

2021-10-12 04:14 UTC, eyeamkd commented on client/__tests__/Deposits.test.jsx
> +const mocks =
Use a separate file for mocks

2021-10-12 04:14 UTC, eyeamkd commented on client/__tests__/addCategory.test.jsx
> +import wait from 'waait';
Where is "wait" being used?

2021-10-12 04:14 UTC, eyeamkd commented on client/__tests__/addMenu.test.jsx
> +    console.log(wrapper.debug())
Please remove console logs

2021-10-12 04:14 UTC, eyeamkd commented on client/__tests__/addStore.test.jsx
> +const mockNewStore = {
Try to keep the mock data in a separate file

2021-10-12 04:14 UTC, eyeamkd commented on client/__tests__/menu.test.jsx
> +        const menuMock =
Import and use the data to have a cleaner looking code

2021-10-12 04:14 UTC, eyeamkd commented on client/__tests__/profile.test.jsx
> +//     expect(wrapper.find("classes.button")).toHaveLength(1);
Remove the code if it's not necessary

2021-10-12 04:14 UTC, eyeamkd commented on client/__tests__/signUp.test.jsx
> +            // addUserPhoneNumber: "7896541230",
Remove commented code if not necessary or mention the reason for the comment

2021-10-12 04:14 UTC, eyeamkd commented on client/__tests__/verifyOrder.test.jsx
> +const paymentModes = ["Cash", "CreditCard", "UPI", "DebitCard", "Check", "NetBanking"]
Use Enums for much use cases

2021-10-12 05:43 UTC, KunalSharma1999 commented on client/__mocks__/styleMock.js
> +module.exports = {};
Stylesheet and image imports cause error while testing in next js. So, to avoid that adding this code in this particular file was the way given to mock them and proceed without error in the next js official testing documentation.

2021-10-12 08:32 UTC, eyeamkd requested changes

2021-10-12 08:32 UTC, eyeamkd commented on client/components/VerifyOrder.js
> +// import { checkDocument } from '@apollo/client/utilities';
Why commenting the import?

2021-10-12 08:32 UTC, eyeamkd commented on client/components/VerifyOrder.js
> +        script.src = 'https://checkout.razorpay.com/v1/checkout.js'
use env variables for all the strings

2021-10-12 08:32 UTC, eyeamkd commented on client/components/VerifyOrder.js
> +        script.src = 'https://checkout.razorpay.com/v1/checkout.js'
or atleast a const folder where you define all your constants

2021-10-15 06:15 UTC, eyeamkd approved these changes

2021-10-16 09:29 UTC, merged